AWSTemplateFormatVersion: 2010-09-09
Description: |
  This is the AWS CFN template for the IB Group Project,
  "Riffr" by Team Papa

########     ###    ########     ###    ##     ##
##     ##   ## ##   ##     ##   ## ##   ###   ###
##     ##  ##   ##  ##     ##  ##   ##  #### ####
########  ##     ## ########  ##     ## ## ### ##
##        ######### ##   ##   ######### ##     ##
##        ##     ## ##    ##  ##     ## ##     ##
##        ##     ## ##     ## ##     ## ##     ##

Parameters:
  
  Stage:
    Description: Development stage
    Type: String
    Default: dev
    AllowedValues: [dev, prod]

  BackendServerPort:
    Description: Port for the Backend Server
    Type: Number
    Default: 10000

  BackendServerSSHKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Name of an existing EC2 KeyPair for SSH access to the Backend Server Instance

  BackendServerAmiId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Default: /aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2

Resources:

 ######   #######  
##    ## ##     ## 
##              ## 
 ######   #######  
      ##        ## 
##    ## ##     ## 
 ######   #######  

  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicRead
      BucketName: !Sub ${AWS::AccountId}-${AWS::StackName}-${Stage}-frontend-bucket
      WebsiteConfiguration: 
        IndexDocument: "index.html"
        ErrorDocument: "index.html"
  
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument: 
        Version: 2012-10-17
        Statement: 
          - Sid: AllowPublicReadAccess
            Effect: Allow
            Principal: "*"
            Action:
              - s3:GetObject
            Resource:
              - !Sub ${FrontendBucket.Arn}/*

########  ######   #######  
##       ##    ## ##     ## 
##       ##              ## 
######   ##        #######  
##       ##       ##        
##       ##    ## ##        
########  ######  ######### 

  BackendEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: !Ref BackendServerSSHKeyName
      ImageId: !Ref BackendServerAmiId
      InstanceType: t2.micro
      SecurityGroupIds:
        - !Ref BackendSecurityGroup


  BackendSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SSH and TCP via Sever Ports 
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: !Ref BackendServerPort
          ToPort: !Ref BackendServerPort
          CidrIp: 0.0.0.0/0

Outputs:

  FrontendUrl:
    Value: !GetAtt FrontendBucket.WebsiteURL
    Description: URL for the frontend website on S3